package pqerror


import (
	"github.com/lib/pq"
)


const (
	CodeSuccessfulCompletion = pq.ErrorCode("00000")

	CodeWarning                                 = pq.ErrorCode("01000")
	CodeWarningDynamicResultSetsReturned        = pq.ErrorCode("0100C")
	CodeWarningImplicitZeroBitPadding           = pq.ErrorCode("01008")
	CodeWarningNullValueEliminatedInSetFunction = pq.ErrorCode("01003")
	CodeWarningPrivilegeNotGranted              = pq.ErrorCode("01007")
	CodeWarningPrivilegeNotRevoked              = pq.ErrorCode("01006")
	CodeWarningStringDataRightTruncation        = pq.ErrorCode("01004")
	CodeWarningDeprecatedFeature                = pq.ErrorCode("01P01")

	CodeNoData                                      = pq.ErrorCode("02000")
	CodeNoDataNoAdditionalDynamicResultSetsReturned = pq.ErrorCode("02001")

	CodeSqlStatementNotYetComplete = pq.ErrorCode("03000")

	CodeConnectionException                                              = pq.ErrorCode("08000")
	CodeConnectionExceptionConnectionDoesNotExist                        = pq.ErrorCode("08003")
	CodeConnectionExceptionConnectionFailure                             = pq.ErrorCode("08006")
	CodeConnectionExceptionSqlclientUnableToEstablishSqlconnection       = pq.ErrorCode("08001")
	CodeConnectionExceptionSqlserverRejectedEstablishmentOfSqlconnection = pq.ErrorCode("08004")
	CodeConnectionExceptionTransactionResolutionUnknown                  = pq.ErrorCode("08007")
	CodeConnectionExceptionProtocolViolation                             = pq.ErrorCode("08P01")

	CodeTriggeredActionException = pq.ErrorCode("09000")

	CodeFeatureNotSupported = pq.ErrorCode("0A000")

	CodeInvalidTransactionInitiation = pq.ErrorCode("0B000")

	CodeLocatorException                            = pq.ErrorCode("0F000")
	CodeLocatorExceptionInvalidLocatorSpecification = pq.ErrorCode("0F001")

	CodeInvalidGrantor                      = pq.ErrorCode("0L000")
	CodeInvalidGrantorInvalidGrantOperation = pq.ErrorCode("0LP01")

	CodeInvalidRoleSpecification = pq.ErrorCode("0P000")

	CodeDiagnosticsException                                               = pq.ErrorCode("0Z000")
	CodeDiagnosticsExceptionStackedDiagnosticsAccessedWithoutActiveHandler = pq.ErrorCode("0Z002")

	CodeCaseNotFound = pq.ErrorCode("20000")

	CodeCardinalityViolation = pq.ErrorCode("21000")

	CodeDataException                                      = pq.ErrorCode("22000")
	CodeDataExceptionArraySubscriptError                   = pq.ErrorCode("2202E")
	CodeDataExceptionCharacterNotInRepertoire              = pq.ErrorCode("22021")
	CodeDataExceptionDatetimeFieldOverflow                 = pq.ErrorCode("22008")
	CodeDataExceptionDivisionByZero                        = pq.ErrorCode("22012")
	CodeDataExceptionErrorInAssignment                     = pq.ErrorCode("22005")
	CodeDataExceptionEscapeCharacterConflict               = pq.ErrorCode("2200B")
	CodeDataExceptionIndicatorOverflow                     = pq.ErrorCode("22022")
	CodeDataExceptionIntervalFieldOverflow                 = pq.ErrorCode("22015")
	CodeDataExceptionInvalidArgumentForLogarithm           = pq.ErrorCode("2201E")
	CodeDataExceptionInvalidArgumentForNtileFunction       = pq.ErrorCode("22014")
	CodeDataExceptionInvalidArgumentForNthValueFunction    = pq.ErrorCode("22016")
	CodeDataExceptionInvalidArgumentForPowerFunction       = pq.ErrorCode("2201F")
	CodeDataExceptionInvalidArgumentForWidthBucketFunction = pq.ErrorCode("2201G")
	CodeDataExceptionInvalidCharacterValueForCast          = pq.ErrorCode("22018")
	CodeDataExceptionInvalidDatetimeFormat                 = pq.ErrorCode("22007")
	CodeDataExceptionInvalidEscapeCharacter                = pq.ErrorCode("22019")
	CodeDataExceptionInvalidEscapeOctet                    = pq.ErrorCode("2200D")
	CodeDataExceptionInvalidEscapeSequence                 = pq.ErrorCode("22025")
	CodeDataExceptionNonstandardUseOfEscapeCharacter       = pq.ErrorCode("22P06")
	CodeDataExceptionInvalidIndicatorParameterValue        = pq.ErrorCode("22010")
	CodeDataExceptionInvalidParameterValue                 = pq.ErrorCode("22023")
	CodeDataExceptionInvalidRegularExpression              = pq.ErrorCode("2201B")
	CodeDataExceptionInvalidRowCountInLimitClause          = pq.ErrorCode("2201W")
	CodeDataExceptionInvalidRowCountInResultOffsetClause   = pq.ErrorCode("2201X")
	CodeDataExceptionInvalidTimeZoneDisplacementValue      = pq.ErrorCode("22009")
	CodeDataExceptionInvalidUseOfEscapeCharacter           = pq.ErrorCode("2200C")
	CodeDataExceptionMostSpecificTypeMismatch              = pq.ErrorCode("2200G")
	CodeDataExceptionNullValueNotAllowed                   = pq.ErrorCode("22004")
	CodeDataExceptionNullValueNoIndicatorParameter         = pq.ErrorCode("22002")
	CodeDataExceptionNumericValueOutOfRange                = pq.ErrorCode("22003")
	CodeDataExceptionStringDataLengthMismatch              = pq.ErrorCode("22026")
	CodeDataExceptionStringDataRightTruncation             = pq.ErrorCode("22001")
	CodeDataExceptionSubstringError                        = pq.ErrorCode("22011")
	CodeDataExceptionTrimError                             = pq.ErrorCode("22027")
	CodeDataExceptionUnterminatedCString                   = pq.ErrorCode("22024")
	CodeDataExceptionZeroLengthCharacterString             = pq.ErrorCode("2200F")
	CodeDataExceptionFloatingPointException                = pq.ErrorCode("22P01")
	CodeDataExceptionInvalidTextRepresentation             = pq.ErrorCode("22P02")
	CodeDataExceptionInvalidBinaryRepresentation           = pq.ErrorCode("22P03")
	CodeDataExceptionBadCopyFileFormat                     = pq.ErrorCode("22P04")
	CodeUntranslatableCharacter                            = pq.ErrorCode("22P05")
	CodeDataExceptionNotAnXmlDocument                      = pq.ErrorCode("2200L")
	CodeDataExceptionInvalidXmlDocument                    = pq.ErrorCode("2200M")
	CodeDataExceptionInvalidXmlContent                     = pq.ErrorCode("2200N")
	CodeDataExceptionInvalidXmlComment                     = pq.ErrorCode("2200S")
	CodeDataExceptionInvalidXmlProcessingInstruction       = pq.ErrorCode("2200T")

	CodeIntegrityConstraintViolation                    = pq.ErrorCode("23000")
	CodeIntegrityConstraintViolationRestrictViolation   = pq.ErrorCode("23001")
	CodeIntegrityConstraintViolationNotNullViolation    = pq.ErrorCode("23502")
	CodeIntegrityConstraintViolationForeignKeyViolation = pq.ErrorCode("23503")
	CodeIntegrityConstraintViolationUniqueViolation     = pq.ErrorCode("23505")
	CodeIntegrityConstraintViolationCheckViolation      = pq.ErrorCode("23514")
	CodeIntegrityConstraintViolationExclusionViolation  = pq.ErrorCode("23P01")

	CodeInvalidCursorState = pq.ErrorCode("24000")

	CodeInvalidTransactionState                                                = pq.ErrorCode("25000")
	CodeInvalidTransactionStateActiveSqlTransaction                            = pq.ErrorCode("25001")
	CodeInvalidTransactionStateBranchTransactionAlreadyActive                  = pq.ErrorCode("25002")
	CodeInvalidTransactionStateHeldCursorRequiresSameIsolationLevel            = pq.ErrorCode("25008")
	CodeInvalidTransactionStateInappropriateAccessModeForBranchTransaction     = pq.ErrorCode("25003")
	CodeInvalidTransactionStateInappropriateIsolationLevelForBranchTransaction = pq.ErrorCode("25004")
	CodeInvalidTransactionStateNoActiveSqlTransactionForBranchTransaction      = pq.ErrorCode("25005")
	CodeInvalidTransactionStateReadOnlySqlTransaction                          = pq.ErrorCode("25006")
	CodeInvalidTransactionStateSchemaAndDataStatementMixingNotSupported        = pq.ErrorCode("25007")
	CodeInvalidTransactionStateNoActiveSqlTransaction                          = pq.ErrorCode("25P01")
	CodeInvalidTransactionStateInFailedSqlTransaction                          = pq.ErrorCode("25P02")

	CodeInvalidSqlStatementName = pq.ErrorCode("26000")

	CodeTriggeredDataChangeViolation = pq.ErrorCode("27000")

	CodeInvalidAuthorizationSpecification                = pq.ErrorCode("28000")
	CodeInvalidAuthorizationSpecificationInvalidPassword = pq.ErrorCode("28P01")

	CodeDependentPrivilegeDescriptorsStillExist                           = pq.ErrorCode("2B000")
	CodeDependentPrivilegeDescriptorsStillExistDependentObjectsStillExist = pq.ErrorCode("2BP01")

	CodeInvalidTransactionTermination = pq.ErrorCode("2D000")

	CodeSqlRoutineException                                  = pq.ErrorCode("2F000")
	CodeSqlRoutineExceptionFunctionExecutedNoReturnStatement = pq.ErrorCode("2F005")
	CodeSqlRoutineExceptionModifyingSqlDataNotPermitted      = pq.ErrorCode("2F002")
	CodeSqlRoutineExceptionProhibitedSqlStatementAttempted   = pq.ErrorCode("2F003")
	CodeSqlRoutineExceptionReadingSqlDataNotPermitted        = pq.ErrorCode("2F004")

	CodeInvalidCursorName = pq.ErrorCode("34000")

	CodeExternalRoutineException                                = pq.ErrorCode("38000")
	CodeExternalRoutineExceptionContainingSqlNotPermitted       = pq.ErrorCode("38001")
	CodeExternalRoutineExceptionModifyingSqlDataNotPermitted    = pq.ErrorCode("38002")
	CodeExternalRoutineExceptionProhibitedSqlStatementAttempted = pq.ErrorCode("38003")
	CodeExternalRoutineExceptionReadingSqlDataNotPermitted      = pq.ErrorCode("38004")

	CodeExternalRoutineInvocationException                        = pq.ErrorCode("39000")
	CodeExternalRoutineInvocationExceptionInvalidSqlstateReturned = pq.ErrorCode("39001")
	CodeExternalRoutineInvocationExceptionNullValueNotAllowed     = pq.ErrorCode("39004")
	CodeExternalRoutineInvocationExceptionTriggerProtocolViolated = pq.ErrorCode("39P01")
	CodeExternalRoutineInvocationExceptionSrfProtocolViolated     = pq.ErrorCode("39P02")

	CodeSavepointException                              = pq.ErrorCode("3B000")
	CodeSavepointExceptionInvalidSavepointSpecification = pq.ErrorCode("3B001")

	CodeInvalidCatalogName = pq.ErrorCode("3D000")

	CodeInvalidSchemaName = pq.ErrorCode("3F000")

	CodeTransactionRollback                                        = pq.ErrorCode("40000")
	CodeTransactionRollbackTransactionIntegrityConstraintViolation = pq.ErrorCode("40002")
	CodeTransactionRollbackSerializationFailure                    = pq.ErrorCode("40001")
	CodeTransactionRollbackStatementCompletionUnknown              = pq.ErrorCode("40003")
	CodeTransactionRollbackDeadlockDetected                        = pq.ErrorCode("40P01")

	CodeSyntaxErrorOrAccessRuleViolation   = pq.ErrorCode("42000")
	CodeSyntaxError                        = pq.ErrorCode("42601")
	CodeInsufficientPrivilege              = pq.ErrorCode("42501")
	CodeCannotCoerce                       = pq.ErrorCode("42846")
	CodeGroupingError                      = pq.ErrorCode("42803")
	CodeWindowingError                     = pq.ErrorCode("42P20")
	CodeInvalidRecursion                   = pq.ErrorCode("42P19")
	CodeInvalidForeignKey                  = pq.ErrorCode("42830")
	CodeInvalidName                        = pq.ErrorCode("42602")
	CodeNameTooLong                        = pq.ErrorCode("42622")
	CodeReservedName                       = pq.ErrorCode("42939")
	CodeDatatypeMismatch                   = pq.ErrorCode("42804")
	CodeIndeterminateDatatype              = pq.ErrorCode("42P18")
	CodeCollationMismatch                  = pq.ErrorCode("42P21")
	CodeIndeterminateCollation             = pq.ErrorCode("42P22")
	CodeWrongObjectType                    = pq.ErrorCode("42809")
	CodeUndefinedColumn                    = pq.ErrorCode("42703")
	CodeUndefinedFunction                  = pq.ErrorCode("42883")
	CodeUndefinedTable                     = pq.ErrorCode("42P01")
	CodeUndefinedParameter                 = pq.ErrorCode("42P02")
	CodeUndefinedObject                    = pq.ErrorCode("42704")
	CodeDuplicateColumn                    = pq.ErrorCode("42701")
	CodeDuplicateCursor                    = pq.ErrorCode("42P03")
	CodeDuplicateDatabase                  = pq.ErrorCode("42P04")
	CodeDuplicateFunction                  = pq.ErrorCode("42723")
	CodeDuplicatePreparedStatement         = pq.ErrorCode("42P05")
	CodeDuplicateSchema                    = pq.ErrorCode("42P06")
	CodeDuplicateTable                     = pq.ErrorCode("42P07")
	CodeDuplicateAlias                     = pq.ErrorCode("42712")
	CodeDuplicateObject                    = pq.ErrorCode("42710")
	CodeAmbiguousColumn                    = pq.ErrorCode("42702")
	CodeAmbiguousFunction                  = pq.ErrorCode("42725")
	CodeAmbiguousParameter                 = pq.ErrorCode("42P08")
	CodeAmbiguousAlias                     = pq.ErrorCode("42P09")
	CodeInvalidColumnReference             = pq.ErrorCode("42P10")
	CodeInvalidColumnDefinition            = pq.ErrorCode("42611")
	CodeInvalidCursorDefinition            = pq.ErrorCode("42P11")
	CodeInvalidDatabaseDefinition          = pq.ErrorCode("42P12")
	CodeInvalidFunctionDefinition          = pq.ErrorCode("42P13")
	CodeInvalidPreparedStatementDefinition = pq.ErrorCode("42P14")
	CodeInvalidSchemaDefinition            = pq.ErrorCode("42P15")
	CodeInvalidTableDefinition             = pq.ErrorCode("42P16")
	CodeInvalidObjectDefinition            = pq.ErrorCode("42P17")

	CodeWithCheckOptionViolation = pq.ErrorCode("44000")

	CodeInsufficientResources                           = pq.ErrorCode("53000")
	CodeInsufficientResourcesDiskFull                   = pq.ErrorCode("53100")
	CodeInsufficientResourcesOutOfMemory                = pq.ErrorCode("53200")
	CodeInsufficientResourcesTooManyConnections         = pq.ErrorCode("53300")
	CodeInsufficientResourcesConfigurationLimitExceeded = pq.ErrorCode("53400")

	CodeProgramLimitExceeded                    = pq.ErrorCode("54000")
	CodeProgramLimitExceededStatementTooComplex = pq.ErrorCode("54001")
	CodeProgramLimitExceededTooManyColumns      = pq.ErrorCode("54011")
	CodeProgramLimitExceededTooManyArguments    = pq.ErrorCode("54023")

	CodeObjectNotInPrerequisiteState                       = pq.ErrorCode("55000")
	CodeObjectNotInPrerequisiteStateObjectInUse            = pq.ErrorCode("55006")
	CodeObjectNotInPrerequisiteStateCantChangeRuntimeParam = pq.ErrorCode("55P02")
	CodeObjectNotInPrerequisiteStateLockNotAvailable       = pq.ErrorCode("55P03")

	CodeOperatorIntervention                 = pq.ErrorCode("57000")
	CodeOperatorInterventionQueryCanceled    = pq.ErrorCode("57014")
	CodeOperatorInterventionAdminShutdown    = pq.ErrorCode("57P01")
	CodeOperatorInterventionCrashShutdown    = pq.ErrorCode("57P02")
	CodeOperatorInterventionCannotConnectNow = pq.ErrorCode("57P03")
	CodeOperatorInterventionDatabaseDropped  = pq.ErrorCode("57P04")

	CodeSystemError              = pq.ErrorCode("58000")
	CodeSystemErrorIoError       = pq.ErrorCode("58030")
	CodeSystemErrorUndefinedFile = pq.ErrorCode("58P01")
	CodeSystemErrorDuplicateFile = pq.ErrorCode("58P02")

	CodeConfigFileError               = pq.ErrorCode("F0000")
	CodeConfigFileErrorLockFileExists = pq.ErrorCode("F0001")

	CodeFdwError                                     = pq.ErrorCode("HV000")
	CodeFdwErrorFdwColumnNameNotFound                = pq.ErrorCode("HV005")
	CodeFdwErrorFdwDynamicParameterValueNeeded       = pq.ErrorCode("HV002")
	CodeFdwErrorFdwFunctionSequenceError             = pq.ErrorCode("HV010")
	CodeFdwErrorFdwInconsistentDescriptorInformation = pq.ErrorCode("HV021")
	CodeFdwErrorFdwInvalidAttributeValue             = pq.ErrorCode("HV024")
	CodeFdwErrorFdwInvalidColumnName                 = pq.ErrorCode("HV007")
	CodeFdwErrorFdwInvalidColumnNumber               = pq.ErrorCode("HV008")
	CodeFdwErrorFdwInvalidDataType                   = pq.ErrorCode("HV004")
	CodeFdwErrorFdwInvalidDataTypeDescriptors        = pq.ErrorCode("HV006")
	CodeFdwErrorFdwInvalidDescriptorFieldIdentifier  = pq.ErrorCode("HV091")
	CodeFdwErrorFdwInvalidHandle                     = pq.ErrorCode("HV00B")
	CodeFdwErrorFdwInvalidOptionIndex                = pq.ErrorCode("HV00C")
	CodeFdwErrorFdwInvalidOptionName                 = pq.ErrorCode("HV00D")
	CodeFdwErrorFdwInvalidStringLengthOrBufferLength = pq.ErrorCode("HV090")
	CodeFdwErrorFdwInvalidStringFormat               = pq.ErrorCode("HV00A")
	CodeFdwErrorFdwInvalidUseOfNullPointer           = pq.ErrorCode("HV009")
	CodeFdwErrorFdwTooManyHandles                    = pq.ErrorCode("HV014")
	CodeFdwErrorFdwOutOfMemory                       = pq.ErrorCode("HV001")
	CodeFdwErrorFdwNoSchemas                         = pq.ErrorCode("HV00P")
	CodeFdwErrorFdwOptionNameNotFound                = pq.ErrorCode("HV00J")
	CodeFdwErrorFdwReplyHandle                       = pq.ErrorCode("HV00K")
	CodeFdwErrorFdwSchemaNotFound                    = pq.ErrorCode("HV00Q")
	CodeFdwErrorFdwTableNotFound                     = pq.ErrorCode("HV00R")
	CodeFdwErrorFdwUnableToCreateExecution           = pq.ErrorCode("HV00L")
	CodeFdwErrorFdwUnableToCreateReply               = pq.ErrorCode("HV00M")
	CodeFdwErrorFdwUnableToEstablishConnection       = pq.ErrorCode("HV00N")

	CodePlpgsqlError               = pq.ErrorCode("P0000")
	CodePlpgsqlErrorRaiseException = pq.ErrorCode("P0001")
	CodePlpgsqlErrorNoDataFound    = pq.ErrorCode("P0002")
	CodePlpgsqlErrorTooManyRows    = pq.ErrorCode("P0003")

	CodeInternalError               = pq.ErrorCode("XX000")
	CodeInternalErrorDataCorrupted  = pq.ErrorCode("XX001")
	CodeInternalErrorIndexCorrupted = pq.ErrorCode("XX002")
)
